version: '3.1'

services:
  db:
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: afo@030571
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
